trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'TestAZ'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage account list'
